FORMAT: 1A
HOST: http://example.org

 <!-- OpenIssue: https://github.com/Aconex/drakov/issues/147 -->

# drawing-battle API Reference
<!-- include(./include/data_structures.apib) -->
<!-- include(./src/answers.apib) -->

<!-- include(./src/predicts.apib) -->
