# Group 予測
## 予測
### 予測結果取得 [POST /d-battle/api/v1/predicts]
+ Request (application/json)
    + Attribute (array, required, fixed-type)
        +  (array, required, fixed-type)
            + (array, required, fixed-type)
                + (number)
                + (number)
                + (number)

+ Response 200 (application/json)
    + Attribute
        + label: うさぎ(string, required)